feat: psreference mapper
mission-apprentissage/catalogue-apprentissage pull request #64
Opened 2021-01-11 18:34 UTC by kevbarns

2021-01-12 07:59 UTC, ericplaquevent commented on server/src/logic/mappers/psReferenceMapper.js
> +          $or: [{ siret_formateur: siret }, { siret_gestionnaire: siret }],
:heart_eyes_cat:

2021-01-12 16:23 UTC, Gethi requested changes
c'est pas bon :) 

### Payload

```
const { cfd, etablissement_formateur_siret, etablissement_gestionnaire_siret} = payload;
```


### Response
```
{
   parcoursup_reference: true|false
}
```


### Error Handling
```
{
   parcoursup_reference: false,
   error: "format du siret faux" | "Cfd invalid" | "le gestionnaire n'est pas retrouvé" | "les sirets sont inversés"| etc...
}
```

2021-01-12 16:24 UTC, Gethi commented
et en plus c'est pas un OR mais bien un 
payload_siret_gest === reconciliation_ siret_gestionnaire
payload_siret_formateur === reconciliation_ siret_formateur
payload_cfd === reconciliation_cfd

2021-01-14 16:31 UTC, Gethi commented on server/src/common/utils/cfdUtils.js
> +};
return true si c'est bon ?

2021-01-14 16:33 UTC, merged